# ########################################################### #
# BetaPlayerReward Plugin Developer: PopoGonry ( rhtjdsh35@gmail.com )
# ########################################################### #

# BetaPlayerReward Plugin Config File #


Is-Server-Beta: true



